### ISSUE TITLE
Switch to https

### ISSUE THREAD

**Issue by silentguy256** [leomoty/SGPP#114]
Steamgifts is now forcing https:// so all references should be updated in the header and all the appropriate places.

**Comment by nikop** [comment]
Fixed

**Comment by Blackbird88** [comment]
What'd you test it on? The SG++ settings is still borked here :(

**Comment by nikop** [comment]
Settings need to be redone or manually imported. Due to security reasons, localStorage can't be shared between http & https pages, so automatic import is not possible.

See this: https://www.steamgifts.com/go/comment/7QI3G6Q

**Comment by Blackbird88** [comment]
Ouch. Well thanks.

**Comment by silentguy256** [comment]
Small problem: It seems you are loading the font needed to display the checkboxes over http? At least firefox by default blocks them as unsecure items in on the settings page

**Comment by Blackbird88** [comment]
Aha so that's the problem. I had trouble clicking into those tiny squares.

**Comment by nikop** [comment]
Fonts should be working now or soon (after cache is refreshed).

**Comment by Blackbird88** [comment]
Oh I had to "Allow loading script from unsecured location" on the page. It was grey shield icon.
