### ISSUE TITLE
EndlessScrollDiscussionReplies doesn't redirects Permalinks properly.

### ISSUE THREAD

**Issue by StamSolid** [leomoty/SGPP#61]
Enabling EndlessScrollDiscussionReplies sorts comments to "newest first" so when you click on permalink of a comment from your messages for example, it won't sent you to where the comment is.
 By the look of it most of the times sents you were the comment supposed to be without the sorting.

**Comment by leomoty** [comment]
@nikop can you give some insight on this?

**Comment by nikop** [comment]
Looks like problem is that it assumes that you always want to view last page.

https://github.com/nikop/SGV2-/commit/cdaa8a02d0a7db5dc3c6b8b279b9b26a28ce2cf5

This fixes it partially, but there's no way to force previous page to load. If linked comment is in second page, you can't read third page. (Or first page if not using newest first / reverse order)

**Comment by leomoty** [comment]
@StamSolid Is it any better? on build 0.2.4 beta?

**Comment by StamSolid** [comment]
@leomoty yeah it does look better. Much better. It redirects straight to the comment (*and without the navbar on top of it* :P ). I noticed that you guys done some sorcery on this.
Only "problem" is the one that nikop describes above. That we have to click to previous page to view it instead of autoloading.
