### ISSUE TITLE
Some URLs not supported by SGPP.location

### ISSUE THREAD

**Issue by nikop** [leomoty/SGPP#83]
http://www.steamgifts.com/group/SJ7Bu/sgifts/wishlist
http://www.steamgifts.com/group/SJ7Bu/sgifts/users
http://www.steamgifts.com/group/SJ7Bu/sgifts

These pages share same location, but needs to be distinguished to be able support endless scroll in these.

{ pageKind: "group", code: "", description: "sgifts", subpage: "SJ7Bu", hash: "", parameters: Object }

**Comment by leomoty** [comment]
I am kinda sick, but i'll try to make this tonight :+1:
