### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by TomskDiver** [leomoty/SGPP#86]
Hi.
I install 0.2.5 beta, but it don't worked. Chrome 42.0.2311.4 dev-m 
In console:
[Mon Mar 02 2015 10:41:44 GMT+0600 (RTZ 5 (зима))] SGPP - Steamgifts++ plugin started.
Uncaught ReferenceError: $ is not defined
May be script start before jquery loadnig?

**Comment by leomoty** [comment]
I am unsure we can safely say anything about a chrome dev build, can you test with the mainline one? It might even be a bug with Tampermonkey...

**Comment by TomskDiver** [comment]
I install stable Chrome version 40.0.2214.115 m. And got message in console:
```javascript
 [Tue Mar 03 2015 09:46:59 GMT+0600 (RTZ 5 (зима))] SGPP - Steamgifts++ plugin started.
script.js:16
Uncaught ReferenceError: $ is not defined script.js:16
b.init script.js:16
c script.js:16
(anonymous function) script.js:16
(anonymous function) script.js:17
```

**Comment by TomskDiver** [comment]
Sorry, i install script direct to chrome extension without Tampermonkey:) I install tampermonkey and script work fine.

**Comment by leomoty** [comment]
Makes sense, no worries :)

2015-03-03 1:05 GMT-03:00 TomskDiver <notifications@github.com>:
