### ISSUE TITLE
Sending Keys on Giveaways

### ISSUE THREAD

**Issue by koalix** [leomoty/SGPP#98]
I create giveaways every month. When the giveaway ends, I can't click at the link to reveal the winner/send keys with the script open.

When I try to do, it brings the giveaway window and doesn't open the page with the send key/confirm gift sent.

Follow a screenshot of what happens.

![image](https://cloud.githubusercontent.com/assets/6993417/8069564/bcff0d2e-0ed1-11e5-8705-3e1569003e85.png)

**Comment by nikop** [comment]
Fixed in 0.4.1
